export const env = {
  UNIVERSITY_API_URL: process.env.NEXT_PUBLIC_UNIVERSITY_API_URL,
  ACCOMMODATION_API_URL: process.env.NEXT_PUBLIC_ACCOMMODATION_API_URL,
  PARTNER_API_URL: process.env.NEXT_PUBLIC_PARTNER_API_URL,
  STUDENT_API_URL: process.env.NEXT_PUBLIC_STUDENT_API_URL,
  AUTH_API_URL: process.env.NEXT_PUBLIC_AUTH_URL


}
