export const getCountryInfo = (countryCode) => {
    const countries = {
        AF: { name: "Afghanistan", img: "https://flagcdn.com/w320/af.png" },
        AL: { name: "Albania", img: "https://flagcdn.com/w320/al.png" },
        DZ: { name: "Algeria", img: "https://flagcdn.com/w320/dz.png" },
        US: { name: "United States", img: "https://flagcdn.com/w320/us.png" },
        CA: { name: "Canada", img: "https://flagcdn.com/w320/ca.png" },
        GB: { name: "United Kingdom", img: "https://flagcdn.com/w320/gb.png" },
        IN: { name: "India", img: "https://flagcdn.com/w320/in.png" },
        PK: { name: "Pakistan", img: "https://flagcdn.com/w320/pk.png" },
        FR: { name: "France", img: "https://lh6.googleusercontent.com/proxy/VSDBMeOlHFia1rVgjtrzdD42kC-HsycxOoAOJ_VCsdrf1eGyS8-438Q3d5ZNb2nr8rNFxLRn6010qqIibO88yCK8tSWGlI9c4nZ4SpC3OuHk_771MhIgkGMUPNdhXZ3ytMcfVc54246Fipdt8_4UvcyhIAcAkKg=w540-h312-n-k-no" },
        DE: { name: "Germany", img: "https://lh5.googleusercontent.com/p/AF1QipMslBMDL6y2w_WQHAAinSht9ldHy2iIuIpIxWBU=w540-h312-n-k-no" },
        AU: { name: "Australia", img: "https://flagcdn.com/w320/au.png" },
        CN: { name: "China", img: "https://flagcdn.com/w320/cn.png" },
        JP: { name: "Japan", img: "https://flagcdn.com/w320/jp.png" },
        RU: { name: "Russia", img: "https://flagcdn.com/w320/ru.png" },
        SA: { name: "Saudi Arabia", img: "https://flagcdn.com/w320/sa.png" },
        BR: { name: "Brazil", img: "https://flagcdn.com/w320/br.png" },
        IT: { name: "Italy", img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRQjR1luJPB0WEKb3mbnHZ3YK7nW3iLvpF8O67vt_IBDCY2cQ5QzDQbyalBTQvsShUgvLiVbtkI_BOtTtipON9skF13Aksvz46kT-ejHA" },
        ES: { name: "Spain", img: "https://flagcdn.com/w320/es.png" },
        MX: { name: "Mexico", img: "https://flagcdn.com/w320/mx.png" },
        ZA: { name: "South Africa", img: "https://flagcdn.com/w320/za.png" },
        KR: { name: "South Korea", img: "https://flagcdn.com/w320/kr.png" },
        TR: { name: "Turkey", img: "https://i.natgeofe.com/k/b4b412f8-fe02-482c-b6d6-e1b579cb7fff/turkey-istanbul.jpg?wp=1&w=1084.125&h=609" },
        ID: { name: "Indonesia", img: "https://flagcdn.com/w320/id.png" },
        IR: { name: "Iran", img: "https://flagcdn.com/w320/ir.png" },
        EG: { name: "Egypt", img: "https://flagcdn.com/w320/eg.png" },
        TH: { name: "Thailand", img: "https://flagcdn.com/w320/th.png" },
        VN: { name: "Vietnam", img: "https://flagcdn.com/w320/vn.png" },
        BD: { name: "Bangladesh", img: "https://flagcdn.com/w320/bd.png" },
        NG: { name: "Nigeria", img: "https://flagcdn.com/w320/ng.png" },
        PL: { name: "Poland", img: "https://lh5.googleusercontent.com/p/AF1QipOBP6SYE8Jr5NCGQc1AOjGP5VwHoDG54AWTVxyg=w540-h312-n-k-no" },
        SE: { name: "Sweden", img: "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSL0gHo2XWEz4OyYaq_MIMri-mTZ2zLjDZZl-CuNO_TCYf3bXVqdPF_WP_64Tf8idkqDYEJNL0lvYswrgw8SCBmf5mm4nJgjkJM9vfs7Q" },
        FI: { name: "Finland", img: "https://lh6.googleusercontent.com/proxy/VaLshTLJVCMfivGs7EbGefL6YDvv2JsABtuZjPBKsiwiczzjOygBq_v9naVrTr9Xs_IkMxdP4xZtl023IPYnEgP7CS6YDwRaHxiR7xvxp3jJydT9RyFKX187epd_K-rA8L56M7ST54mQto-wYN3ffKOLqTtDsg=w540-h312-n-k-no" },
        NO: { name: "Norway", img: "https://lh5.googleusercontent.com/p/AF1QipNLZS6OspHh2wJDxWFDK3tnK6chKG_BfVsphCD2=w540-h312-n-k-no" },
        CY: { name: "Cyprus", img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcSvW6YyulARSX2wvjSG6J92tuUocObrmNAXj9uHhg0qLhXK2Dh412GpiVaI-7AAnTrqaDpIBIL4UkXhAwW8tqq7mU5CpfwsgXdPkYyxCw" },      
    };

    return countries[countryCode.toUpperCase()] || { name: "Unknown Country", img: "" };
};
